name: Feature request
description: Suggest an idea for the app itself
labels: enhancement
body:
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
        required: true
      - label: I have checked that this issue isn't addressed in any other issue or pull request.
        required: true
- type: textarea
  attributes: 
    label: Related Problem(s)
    description: 💥 Are there any problems that cooerced you into filing this feature request?
- type: textarea
  attributes: 
    label: Description
    description: 🤓 So... what's the request?
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives
    description: 👁️‍🗨️ Is there really no other way? Got any workarounds while the request remains unimplemented?
  validations:
    required: true
